{{- if .Values.service.external.enabled -}}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "spring-rest-hellworld.fullname" . }}
  labels:
    {{- include "spring-rest-hellworld.labels" . | nindent 4 }}
subsets: 
  -
    addresses:
      -
        ip: {{ .Values.service.external.ip }}
    ports:
      -
        port: {{ .Values.service.external.ports.api.externalPort }}
        name: {{ .Values.service.external.ports.api.name }}
{{- end -}}
