apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-rest-hellworld.fullname" . }}-secret
  labels:
    {{- include "spring-rest-hellworld.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.app.secret.subPath | quote }}: {{ printf "mysql:\n  username=%s\n password=%s" .Values.secret.mysqlUsername .Values.secret.mysqlPassword | b64enc }}