apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-rest-hellworld.fullname" . }}
  labels:
    {{- include "spring-rest-hellworld.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $port := .Values.service.ports }}
    - port: {{ $port.externalPort }}
      targetPort: {{ $port.internalPort }}
      protocol: TCP
      name: {{ $port.name }}
    {{- end }}
{{- if not .Values.service.external.enabled }}
  selector:
    {{- include "spring-rest-hellworld.selectorLabels" . | nindent 4 }}
{{- end -}}
