management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: tru
server:
  port: 8082
  servlet:
    contextPath: /spring-rest-hellworld
test-secret:
  username: mutu
  password: 123456
